#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2012 OpenWrt.org

START=99
STOP=02

APPID="2882303761517844579"
PLUGINROOT="/userdisk/appdata/$APPID"

EXTRA_COMMANDS="status"

start() {
    nohup $PLUGINROOT/ss/script/SSSupervisor >/dev/null 2>&1 &
}

stop() {
    $PLUGINROOT/ss/script/ss stop
    killall SSSupervisor
}

restart() {
    stop
    sleep 3
    start
}

status() {
    localpid=$(pidof ss-local)
    redirpid=$(pidof ss-redir)
    if [ -n "$localpid" -a -n "$redirpid" ]; then
        return 1;
    fi
    return 0;
}
