#!/bin/sh
APPID="2882303761517844579"
PLUGINROOT="/userdisk/appdata/$APPID"
while :
do
# do something

ON=`cat $PLUGINROOT/ss/config/enableSS`
echo $ON
    localpid=$(pidof ss-local)
    redirpid=$(pidof ss-redir)

if [ "$ON" == "ON" ]; then
    if [ -n "$localpid" -a -n "$redirpid" ]; then
            echo $localpid >$PLUGINROOT/ss_local_pid
            echo $redirpid >$PLUGINROOT/ss_redir_pid
            echo "SS is runing"
    else
        echo "starting SS"
        $PLUGINROOT/ss/script/ss start >>  $PLUGINROOT/running.log
    fi
elif [ "$ON" == "RESTART" ]; then
    if [ -n "$localpid" -a -n "$redirpid" ]; then
        $PLUGINROOT/ss/script/ss restart >>  $PLUGINROOT/running.log
        echo "restarting SS"
        echo "ON">$PLUGINROOT/ss/config/enableSS
    fi
else
    if [ -n "$localpid" -a -n "$redirpid" ]; then
        $PLUGINROOT/ss/script/ss stop >>  $PLUGINROOT/running.log
        echo "stopping SS"
    fi

fi

sleep 1

done